spring:
  application:
    name: truenas-admin-worker
  main:
    web-application-type: none
  threads:
    virtual:
      enabled: true
  config:
    import: optional:file:.env[.properties]
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

truenas:
  api:
    url: ${TRUENAS_URL}
    key: ${TRUENAS_API_KEY}
    connect-timeout-seconds: 5
    read-timeout-seconds: 15

bot:
  token: ${BOT_TOKEN}
  security:
    admin-chat-id: ${ADMIN_CHAT_ID}

messaging:
  queues:
    incoming: telegram.updates
    outgoing: telegram.replies

logging:
  level:
    org.kuxa.truenasadminworker: DEBUG
